This is a makedown formatted cell.

# Cleasing up 2024 election data

In [18]:
import pandas as pd

In [27]:
import numpy as np

Check pandas works

In [19]:
s1 = pd.Series([[3,45,2,1]])
print(s1)

0    [3, 45, 2, 1]
dtype: object

Now lets see if we can read in the election data. First prepare the CSV file.

In a terminal 
```python
cd Datasets/
cd election\ 2024/
python extract.py > all.csv
```

Now try to import the data using pandas. For this dataset we need a couple of options, using a custom separator, and telling it not to treat the first row as header row.

In [20]:
df = pd.read_csv('Datasets/election 2024/all.csv',sep='|',header=None)
print(df.shape)

(3068, 7)

Now add the header row.

In [21]:
df.columns=["Constituancy","Party","Candidate","winning","votes","percentage","change"]

In [22]:
df.head(10)

,Constituancy,Party,Candidate,winning,votes,percentage,change
0,The Wrekin,Conservative Party,Mark Pritchard,NaN,"16,320",32.6,-32.1
1,The Wrekin,Labour Party,Roh Yakobi,NaN,"15,437",30.9,+6.6
2,The Wrekin,Reform UK,Richard Leppington,NaN,"9,920",19.8,+19.8
3,The Wrekin,Liberal Democrats,Anthony Lowe,NaN,"4,757",9.5,+1.5
4,The Wrekin,Green Party of England and Wales,Patrick McCarthy,NaN,"3,028",6.1,+3.2
5,The Wrekin,Independent,Chris Shipley,NaN,883,NaN,NaN
6,North Shropshire,Liberal Democrats,Helen Morgan,winning,"26,214",52.9,+42.5
7,North Shropshire,Conservative Party,Simon Baynes,NaN,"10,903",22.0,-39.07
8,North Shropshire,Reform UK,Mark Whittle,NaN,"7,687",15.5,+15.5
9,North Shropshire,Labour Party,Natalie Rowley,NaN,"3,423",6.9,-15.5

In [23]:
df.loc[11]

Constituancy          North Shropshire
Party           Independent politician
Candidate           Samuel Cladingbowl
winning                            NaN
votes                              NaN
percentage                         NaN
change                             NaN
Name: 11, dtype: object

There are many rows with some missing data. Lets first find how bad the problem is

In [24]:
print(df.isnull().sum())

Constituancy       0
Party             12
Candidate          0
winning         2825
votes            757
percentage       842
change          1718
dtype: int64

THe winning field only has data when its they have won, so currently its either saying "winning" or NaN.

Lets tidy it up to be true or false. First we get a DataSeries for the

In [25]:
win = df["winning"].notna()
df["winning"]=win
df.head(10)

,Constituancy,Party,Candidate,winning,votes,percentage,change
0,The Wrekin,Conservative Party,Mark Pritchard,False,"16,320",32.6,-32.1
1,The Wrekin,Labour Party,Roh Yakobi,False,"15,437",30.9,+6.6
2,The Wrekin,Reform UK,Richard Leppington,False,"9,920",19.8,+19.8
3,The Wrekin,Liberal Democrats,Anthony Lowe,False,"4,757",9.5,+1.5
4,The Wrekin,Green Party of England and Wales,Patrick McCarthy,False,"3,028",6.1,+3.2
5,The Wrekin,Independent,Chris Shipley,False,883,NaN,NaN
6,North Shropshire,Liberal Democrats,Helen Morgan,True,"26,214",52.9,+42.5
7,North Shropshire,Conservative Party,Simon Baynes,False,"10,903",22.0,-39.07
8,North Shropshire,Reform UK,Mark Whittle,False,"7,687",15.5,+15.5
9,North Shropshire,Labour Party,Natalie Rowley,False,"3,423",6.9,-15.5

In [37]:
df2 = df[df["votes"].notna()]

In [40]:
df2.shape

(2311, 7)